services:
  db:
    ports:
      - "5433:5432"
    restart: "no"

  adminer:
    ports:
      - "8080:8080"
    restart: "no"

  api:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./
          action: sync
          target: /chatapi
          ignore:
            - ./app/.venv
            - .venv
            - ./app/alembic
        - path: ./pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./htmlcov:/chatapi/htmlcov
      - ./app/alembic:/chatapi/app/alembic


networks:
  default:
