services:
  db:
    ports:
      - "5432:5432"
    restart: "no"

  adminer:
    ports:
      - "8080:8080"
    restart: "no"

  chatapi:
    ports:
      - "8000:8000"
    build:
      context: ./chatapi
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./chatapi
          action: sync
          target: /app
          ignore:
            - ./chatapi/.venv
            - .venv
        - path: ./chatapi/pyproject.toml
          action: rebuild
    volumes:
      - ./chatapi/htmlcov:/app/htmlcov
    restart: "no"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  default:
