services:
  db:
    ports:
      - "5433:5432"
    restart: "no"

  adminer:
    ports:
      - "8080:8080"
    restart: "no"

  api:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
      - --timeout-graceful-shutdown
      - "0"
    develop:
      watch:
        - path: ./
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./htmlcov:/app/htmlcov


networks:
  default:
