services:
  db:
    ports:
      - "5433:5432"
    restart: "no"

  adminer:
    ports:
      - "8080:8080"
    restart: "no"

  chatapi:
    ports:
      - "8000:8000"
    build:
      context: ./
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./
          action: sync
          target: /app
          ignore:
            - ./venv
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    volumes:
      - ./htmlcov:/app/htmlcov
    restart: "no"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  default:
