"""Migrate to sql alquemy

Revision ID: 748b8a28f2bb
Revises: f194a7f8daba
Create Date: 2025-05-23 05:59:52.078247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '748b8a28f2bb'
down_revision = 'f194a7f8daba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pgcrypto extension
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')

    op.create_table('clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('encryption_mode', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('apiclient')
    op.alter_column('message', 'content_type',
               existing_type=postgresql.ENUM('text', 'image', 'file', 'video', name='contenttype'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('text', 'image', 'file', 'video', name='contenttype'),
               existing_nullable=True)
    op.create_table('apiclient',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('encryption_mode', postgresql.ENUM('E2EE', 'NONE', name='encryptionmode'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apiclient_pkey')
    )
    op.drop_table('clients')
    # ### end Alembic commands ###
