"""changes in modeling

Revision ID: 909bdb7b9680
Revises: 695ac34bab55
Create Date: 2025-07-03 07:31:43.639071

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '909bdb7b9680'
down_revision = '695ac34bab55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rooms_client_id', 'rooms', ['client_id'], unique=False)
    op.create_index('idx_rooms_created_by_user_id', 'rooms', ['created_by_user_id'], unique=False)
    op.create_index('idx_rooms_is_active', 'rooms', ['is_active'], unique=False)
    op.create_index('idx_rooms_last_message_at', 'rooms', ['last_message_at'], unique=False)
    op.create_index('idx_rooms_room_type', 'rooms', ['room_type'], unique=False)
    op.create_table('scoped_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('scoped_api_key', sa.String(length=255), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'user_id', name='uq_client_user_scoped_key'),
    sa.UniqueConstraint('scoped_api_key')
    )
    op.create_index('idx_scoped_keys_api_key', 'scoped_keys', ['scoped_api_key'], unique=False)
    op.create_index('idx_scoped_keys_client_id', 'scoped_keys', ['client_id'], unique=False)
    op.create_index('idx_scoped_keys_is_active', 'scoped_keys', ['is_active'], unique=False)
    op.create_index('idx_scoped_keys_user_id', 'scoped_keys', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_mime_type', sa.String(length=100), nullable=True),
    sa.Column('reply_to_id', sa.UUID(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('sender_user_id', sa.String(length=255), nullable=False),
    sa.Column('sender_display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_content_type', 'messages', ['content_type'], unique=False)
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_is_deleted', 'messages', ['is_deleted'], unique=False)
    op.create_index('idx_messages_reply_to_id', 'messages', ['reply_to_id'], unique=False)
    op.create_index('idx_messages_room_active', 'messages', ['room_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index('idx_messages_room_created', 'messages', ['room_id', 'created_at'], unique=False)
    op.create_index('idx_messages_room_id', 'messages', ['room_id'], unique=False)
    op.create_index('idx_messages_sender_user_id', 'messages', ['sender_user_id'], unique=False)
    op.create_table('room_memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_read_message_id', sa.UUID(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_user_membership')
    )
    op.create_index('idx_room_memberships_is_active', 'room_memberships', ['is_active'], unique=False)
    op.create_index('idx_room_memberships_last_read_message_id', 'room_memberships', ['last_read_message_id'], unique=False)
    op.create_index('idx_room_memberships_role', 'room_memberships', ['role'], unique=False)
    op.create_index('idx_room_memberships_room_id', 'room_memberships', ['room_id'], unique=False)
    op.create_index('idx_room_memberships_user_id', 'room_memberships', ['user_id'], unique=False)
    op.drop_table('message')
    op.add_column('clients', sa.Column('master_api_key', sa.String(length=255), nullable=False))
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('idx_clients_is_active', 'clients', ['is_active'], unique=False)
    op.create_index('idx_clients_master_api_key', 'clients', ['master_api_key'], unique=False)
    op.create_unique_constraint(None, 'clients', ['master_api_key'])
    op.drop_column('clients', 'api_key')
    op.drop_column('clients', 'encryption_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('encryption_mode', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_index('idx_clients_master_api_key', table_name='clients')
    op.drop_index('idx_clients_is_active', table_name='clients')
    op.alter_column('clients', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'is_active')
    op.drop_column('clients', 'master_api_key')
    op.create_table('message',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('encrypted_payload', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('delivered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('read_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    op.drop_index('idx_room_memberships_user_id', table_name='room_memberships')
    op.drop_index('idx_room_memberships_room_id', table_name='room_memberships')
    op.drop_index('idx_room_memberships_role', table_name='room_memberships')
    op.drop_index('idx_room_memberships_last_read_message_id', table_name='room_memberships')
    op.drop_index('idx_room_memberships_is_active', table_name='room_memberships')
    op.drop_table('room_memberships')
    op.drop_index('idx_messages_sender_user_id', table_name='messages')
    op.drop_index('idx_messages_room_id', table_name='messages')
    op.drop_index('idx_messages_room_created', table_name='messages')
    op.drop_index('idx_messages_room_active', table_name='messages')
    op.drop_index('idx_messages_reply_to_id', table_name='messages')
    op.drop_index('idx_messages_is_deleted', table_name='messages')
    op.drop_index('idx_messages_created_at', table_name='messages')
    op.drop_index('idx_messages_content_type', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_scoped_keys_user_id', table_name='scoped_keys')
    op.drop_index('idx_scoped_keys_is_active', table_name='scoped_keys')
    op.drop_index('idx_scoped_keys_client_id', table_name='scoped_keys')
    op.drop_index('idx_scoped_keys_api_key', table_name='scoped_keys')
    op.drop_table('scoped_keys')
    op.drop_index('idx_rooms_room_type', table_name='rooms')
    op.drop_index('idx_rooms_last_message_at', table_name='rooms')
    op.drop_index('idx_rooms_is_active', table_name='rooms')
    op.drop_index('idx_rooms_created_by_user_id', table_name='rooms')
    op.drop_index('idx_rooms_client_id', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
