"""Add notifications and webhooks

Revision ID: b891ea4bdb80
Revises: 90f6d21868be
Create Date: 2025-07-11 12:32:54.535280

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b891ea4bdb80'
down_revision = '90f6d21868be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('cc', sa.JSON(), nullable=True),
    sa.Column('bcc', sa.JSON(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('email_fallback', sa.JSON(), nullable=True),
    sa.Column('max_retry_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_client_id', 'notifications', ['client_id'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_priority', 'notifications', ['priority'], unique=False)
    op.create_index('ix_notifications_scheduled_at', 'notifications', ['scheduled_at'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('subscribed_events', sa.JSON(), nullable=False),
    sa.Column('max_retry_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_client_webhook_name')
    )
    op.create_index('ix_webhook_endpoints_client_id', 'webhook_endpoints', ['client_id'], unique=False)
    op.create_index('ix_webhook_endpoints_status', 'webhook_endpoints', ['status'], unique=False)
    op.create_index('ix_webhook_endpoints_url', 'webhook_endpoints', ['url'], unique=False)
    op.create_table('notification_delivery_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_attempts_attempted_at', 'notification_delivery_attempts', ['attempted_at'], unique=False)
    op.create_index('ix_delivery_attempts_notification_id', 'notification_delivery_attempts', ['notification_id'], unique=False)
    op.create_index('ix_delivery_attempts_status', 'notification_delivery_attempts', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'event_id', name='uq_endpoint_event')
    )
    op.create_index('ix_webhook_events_created_at', 'webhook_events', ['created_at'], unique=False)
    op.create_index('ix_webhook_events_endpoint_id', 'webhook_events', ['endpoint_id'], unique=False)
    op.create_index('ix_webhook_events_event_type', 'webhook_events', ['event_type'], unique=False)
    op.create_index('ix_webhook_events_scheduled_at', 'webhook_events', ['scheduled_at'], unique=False)
    op.create_index('ix_webhook_events_status', 'webhook_events', ['status'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('successful_deliveries', sa.Integer(), nullable=False),
    sa.Column('failed_deliveries', sa.Integer(), nullable=False),
    sa.Column('average_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'period_start', name='uq_endpoint_period')
    )
    op.create_index('ix_webhook_logs_endpoint_id', 'webhook_logs', ['endpoint_id'], unique=False)
    op.create_index('ix_webhook_logs_period', 'webhook_logs', ['period_start', 'period_end'], unique=False)
    op.create_table('webhook_delivery_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['webhook_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_delivery_attempts_attempted_at', 'webhook_delivery_attempts', ['attempted_at'], unique=False)
    op.create_index('ix_webhook_delivery_attempts_endpoint_id', 'webhook_delivery_attempts', ['endpoint_id'], unique=False)
    op.create_index('ix_webhook_delivery_attempts_event_id', 'webhook_delivery_attempts', ['event_id'], unique=False)
    op.create_index('ix_webhook_delivery_attempts_status', 'webhook_delivery_attempts', ['status'], unique=False)
    op.add_column('clients', sa.Column('email_provider_configs', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('rooms', sa.Column('deactivated_reason', sa.String(length=50), nullable=True))
    op.add_column('rooms', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'deactivated_at')
    op.drop_column('rooms', 'deactivated_reason')
    op.drop_column('clients', 'email_provider_configs')
    op.drop_index('ix_webhook_delivery_attempts_status', table_name='webhook_delivery_attempts')
    op.drop_index('ix_webhook_delivery_attempts_event_id', table_name='webhook_delivery_attempts')
    op.drop_index('ix_webhook_delivery_attempts_endpoint_id', table_name='webhook_delivery_attempts')
    op.drop_index('ix_webhook_delivery_attempts_attempted_at', table_name='webhook_delivery_attempts')
    op.drop_table('webhook_delivery_attempts')
    op.drop_index('ix_webhook_logs_period', table_name='webhook_logs')
    op.drop_index('ix_webhook_logs_endpoint_id', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index('ix_webhook_events_status', table_name='webhook_events')
    op.drop_index('ix_webhook_events_scheduled_at', table_name='webhook_events')
    op.drop_index('ix_webhook_events_event_type', table_name='webhook_events')
    op.drop_index('ix_webhook_events_endpoint_id', table_name='webhook_events')
    op.drop_index('ix_webhook_events_created_at', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_delivery_attempts_status', table_name='notification_delivery_attempts')
    op.drop_index('ix_delivery_attempts_notification_id', table_name='notification_delivery_attempts')
    op.drop_index('ix_delivery_attempts_attempted_at', table_name='notification_delivery_attempts')
    op.drop_table('notification_delivery_attempts')
    op.drop_index('ix_webhook_endpoints_url', table_name='webhook_endpoints')
    op.drop_index('ix_webhook_endpoints_status', table_name='webhook_endpoints')
    op.drop_index('ix_webhook_endpoints_client_id', table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_scheduled_at', table_name='notifications')
    op.drop_index('ix_notifications_priority', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_client_id', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
