"""default created_at

Revision ID: cd06c6ff5781
Revises: 909bdb7b9680
Create Date: 2025-07-03 16:54:02.509708

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd06c6ff5781'
down_revision = '909bdb7b9680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
